/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: test.h
  Source: test.idl
  Cyclone DDS: V0.7.0

*****************************************************************/

#include "dds/ddsc/dds_public_impl.h"

#ifndef _DDSL_TEST_H_
#define _DDSL_TEST_H_


#ifdef __cplusplus
extern "C" {
#endif


typedef struct TestData_Msg
{
  int16_t short_field;
  int32_t long_field;
  uint16_t ushort_field;
  uint32_t ulong_field;
  float float_field;
  double double_field;
  char char_field;
  bool bool_field;
  uint8_t octet_field;
  char * string_field;
  dds_sequence_t sequence_field;
} TestData_Msg;

extern const dds_topic_descriptor_t TestData_Msg_desc;

#define TestData_Msg__alloc() \
((TestData_Msg*) dds_alloc (sizeof (TestData_Msg)));

#define TestData_Msg_free(d,o) \
dds_sample_free ((d), &TestData_Msg_desc, (o))


typedef struct TestData_Inner_InnerMsg
{
  int32_t userID;
  char * message;
} TestData_Inner_InnerMsg;



typedef struct TestData_Inner_TopicMsg
{
  TestData_Inner_InnerMsg inner_msg;
  char * topicID;
} TestData_Inner_TopicMsg;

extern const dds_topic_descriptor_t TestData_Inner_TopicMsg_desc;

#define TestData_Inner_TopicMsg__alloc() \
((TestData_Inner_TopicMsg*) dds_alloc (sizeof (TestData_Inner_TopicMsg)));

#define TestData_Inner_TopicMsg_free(d,o) \
dds_sample_free ((d), &TestData_Inner_TopicMsg_desc, (o))

#ifdef __cplusplus
}
#endif
#endif /* _DDSL_TEST_H_ */
